export const defaultFormularioValues = {
  nombre: '',
  primerApellido: '',
  segundoApellido: '',
  lugarNacimiento: '',
  estadoCivil: '',
  nacionalidad: '',
  fechaRegistro: '',
  fechaNacimiento: '',
  tipoDocumento: '',
  numeroDocumento: '',
  fechaExpedicionDocumento: '',
  fechaCaducidadDocumento: '',
  autoridadEmisoraDocumento: '',
  domicilios: [],
}
